version: '3'
services:
    caddy:
        build: .
        image: ghcr.io/starp-w/caddy-with-cf
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
        network_mode: host
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./Webdata:/www
            - tlsvolume:/caddydata
        # container_name: caddy
    xray:
        image: teddysun/xray:latest
        network_mode: host
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
        volumes:
            - ./config.json:/etc/xray/config.json
            - tlsvolume:/tls
        # container_name: xray
        depends_on: 
            - caddy
    

volumes:
    tlsvolume: